id: I80856F89
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T22:31:07+00:00'
last_modified: '2022-06-08T10:20:35.518729+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25246
  title: ཡིག་རིགས་གསུམ་ལྡན་གྱི་གཟུངས་སྔགས་སོགས་བཀྲས་ལྷུན་དགོན་གྱི་བྲིས་རྒྱུན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D898:
      image_group_id: I1PD36418
      title: ''
      total_pages: 198
      order: 1
      base_file: D898.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
