id: P009343
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:34:21.859515
source_metadata:
  id: bdr:W25246
  title: ཡིག་རིགས་གསུམ་ལྡན་གྱི་གཟུངས་སྔགས་སོགས་བཀྲས་ལྷུན་དགོན་གྱི་བྲིས་རྒྱུན
  author: ''
  volumes:
    94d2dde25872490c930072f61f7d3d7c:
      image_group_id: I1PD36418
      title: ''
      volume_number: 1
      total_pages: 198
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
